# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 889)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 981, 831))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Input_ip = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Input_ip.setObjectName("Input_ip")
        self.horizontalLayout.addWidget(self.Input_ip)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Input_port = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Input_port.setObjectName("Input_port")
        self.horizontalLayout.addWidget(self.Input_port)
        self.Button_connect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_connect.setObjectName("Button_connect")
        self.horizontalLayout.addWidget(self.Button_connect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.Input_username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Input_username.setObjectName("Input_username")
        self.horizontalLayout_2.addWidget(self.Input_username)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.Input_password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Input_password.setObjectName("Input_password")
        self.horizontalLayout_2.addWidget(self.Input_password)
        self.Button_quit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_quit.setObjectName("Button_quit")
        self.horizontalLayout_2.addWidget(self.Button_quit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.radio_pasv = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_pasv.setChecked(True)
        self.radio_pasv.setObjectName("radio_pasv")
        self.verticalLayout.addWidget(self.radio_pasv)
        self.radio_port = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_port.setObjectName("radio_port")
        self.verticalLayout.addWidget(self.radio_port)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.Prompt = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.Prompt.setObjectName("Prompt")
        self.verticalLayout.addWidget(self.Prompt)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Line_directory_local = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Line_directory_local.setReadOnly(True)
        self.Line_directory_local.setObjectName("Line_directory_local")
        self.horizontalLayout_8.addWidget(self.Line_directory_local)
        self.Button_browse_local = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_browse_local.setObjectName("Button_browse_local")
        self.horizontalLayout_8.addWidget(self.Button_browse_local)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.List_local = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.List_local.setObjectName("List_local")
        self.verticalLayout_2.addWidget(self.List_local)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Button_mkdir_local = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_mkdir_local.setObjectName("Button_mkdir_local")
        self.horizontalLayout_6.addWidget(self.Button_mkdir_local)
        self.Button_rmdir_local = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_rmdir_local.setObjectName("Button_rmdir_local")
        self.horizontalLayout_6.addWidget(self.Button_rmdir_local)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Button_store_local = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_store_local.setObjectName("Button_store_local")
        self.horizontalLayout_7.addWidget(self.Button_store_local)
        self.Button_refresh_local = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_refresh_local.setObjectName("Button_refresh_local")
        self.horizontalLayout_7.addWidget(self.Button_refresh_local)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.Line_directory_server = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Line_directory_server.setReadOnly(True)
        self.Line_directory_server.setObjectName("Line_directory_server")
        self.verticalLayout_3.addWidget(self.Line_directory_server)
        self.List_server = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.List_server.setObjectName("List_server")
        self.verticalLayout_3.addWidget(self.List_server)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Button_mkdir_server = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_mkdir_server.setObjectName("Button_mkdir_server")
        self.horizontalLayout_4.addWidget(self.Button_mkdir_server)
        self.Button_rmdir_server = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_rmdir_server.setObjectName("Button_rmdir_server")
        self.horizontalLayout_4.addWidget(self.Button_rmdir_server)
        self.Button_stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_stop.setObjectName("Button_stop")
        self.horizontalLayout_4.addWidget(self.Button_stop)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Button_rename_server = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_rename_server.setObjectName("Button_rename_server")
        self.horizontalLayout_5.addWidget(self.Button_rename_server)
        self.Button_retrieve_server = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_retrieve_server.setObjectName("Button_retrieve_server")
        self.horizontalLayout_5.addWidget(self.Button_retrieve_server)
        self.Button_refresh_server = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_refresh_server.setObjectName("Button_refresh_server")
        self.horizontalLayout_5.addWidget(self.Button_refresh_server)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.Tasks = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.Tasks.setObjectName("Tasks")
        self.Tasks.setColumnCount(0)
        self.Tasks.setRowCount(0)
        self.Tasks.horizontalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.Tasks)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.label_2.setText(_translate("MainWindow", "PORT"))
        self.Button_connect.setText(_translate("MainWindow", "Connect"))
        self.label_3.setText(_translate("MainWindow", "Username"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.Button_quit.setText(_translate("MainWindow", "Quit"))
        self.label_9.setText(_translate("MainWindow", "Select Mode"))
        self.radio_pasv.setText(_translate("MainWindow", "PASV"))
        self.radio_port.setText(_translate("MainWindow", "PORT"))
        self.label_5.setText(_translate("MainWindow", "Prompt"))
        self.label_6.setText(_translate("MainWindow", "Local Files"))
        self.Button_browse_local.setText(_translate("MainWindow", "browse"))
        self.Button_mkdir_local.setText(_translate("MainWindow", "mkdir"))
        self.Button_rmdir_local.setText(_translate("MainWindow", "delete"))
        self.Button_store_local.setText(_translate("MainWindow", "store"))
        self.Button_refresh_local.setText(_translate("MainWindow", "refresh"))
        self.label_7.setText(_translate("MainWindow", "Server Files"))
        self.Button_mkdir_server.setText(_translate("MainWindow", "mkdir"))
        self.Button_rmdir_server.setText(_translate("MainWindow", "rmdir"))
        self.Button_stop.setText(_translate("MainWindow", "stop_transmission"))
        self.Button_rename_server.setText(_translate("MainWindow", "rename"))
        self.Button_retrieve_server.setText(_translate("MainWindow", "retrieve"))
        self.Button_refresh_server.setText(_translate("MainWindow", "refresh"))
        self.label_8.setText(_translate("MainWindow", "Tasks"))

